import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
import { displayCourseName } from "../data/routine";
import { mergeConsecutiveLabEntries, routineTimeKey } from "./routine-merge";

type Entry = {
  day: string;
  time: string;
  courseSection: string;
  teacher: string;
  room: string;
  courseName?: string;
};

const DAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const clean = (v: unknown) => String(v ?? "").replace(/\s+/g, " ").trim();

function dayIndex(day: string) {
  const i = DAYS.findIndex((d) => d.toLowerCase() === clean(day).toLowerCase());
  return i === -1 ? 99 : i;
}

// Handles 08:30-10:00, 8:30 AM-10:00 AM, 01:00-04:00, etc.
function timeKey(value: string) {
  return routineTimeKey(value);
}

function displayCourse(value: string, explicitName?: string) {
  // Always show the human-readable course name first, followed by the exact code + section.
  return displayCourseName(value, explicitName);
}

function groupEntries(entries: Entry[]) {
  // Sort first so two consecutive source slots are adjacent even if the extractor
  // returned them out of order, then collapse continuous LAB slots.
  const sourceSorted = [...entries].sort((a, b) => {
    const d = dayIndex(a.day) - dayIndex(b.day);
    if (d) return d;
    const t = timeKey(a.time) - timeKey(b.time);
    if (t) return t;
    return clean(a.courseSection).localeCompare(clean(b.courseSection));
  });
  const sorted = mergeConsecutiveLabEntries(sourceSorted);

  const groups: { day: string; entries: Entry[] }[] = [];
  for (const entry of sorted) {
    const day = clean(entry.day) || "Unknown";
    let g = groups.find((x) => x.day.toLowerCase() === day.toLowerCase());
    if (!g) {
      g = { day, entries: [] };
      groups.push(g);
    }
    g.entries.push(entry);
  }
  return groups;
}

function displaySourceVersion(name: string) {
  const value = clean(name);
  const match = value.match(/\bversion\s+(.+)$/i);
  if (match) return match[1].trim();
  // Backward compatibility for old database entries.
  const direct = value.match(/\b(v?\d+(?:\.\d+)*(?:[a-z])?)\b/i);
  return direct ? direct[1].toUpperCase() : value;
}

export async function buildRoutinePdf(opts: {
  title: string;
  subject: string;
  version: { name: string };
  entries: Entry[];
  filename: string;
  teacherMode?: boolean;
}) {
  // Collapse consecutive duplicate lab slots before measuring the single-page table.
  const groups = groupEntries(opts.entries);
  const chunks: Buffer[] = [];

  // Landscape A4 gives enough width for the exact 5-column timetable.
  const doc = new PDFDocument({
    size: "A4",
    layout: "landscape",
    margin: 0,
    info: { Title: opts.title, Author: "Routine Hub" },
  });

  doc.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  const W = 841.89;
  const H = 595.28;
  const left = 32;
  const right = W - 32;
  const contentW = right - left;

  const C = {
    navy: "#163B73",
    blue: "#2457A6",
    blue2: "#1B4B8C",
    ink: "#202936",
    muted: "#687385",
    line: "#2B3A4E",
    lightLine: "#B7C1CF",
    soft: "#F4F7FB",
    white: "#FFFFFF",
  };

  // Day | Course | Time Slot | Room | Teacher
  const widths = [92, 370, 112, 102, contentW - 92 - 370 - 112 - 102];
  const labels = ["Day", "Course", "Time Slot", "Room", "Teacher"];

  // ---------- Compact, single-page header ----------
  doc.rect(0, 0, W, 7).fill(C.navy);

  // Routine Hub official logo. The PDF renderer needs a local PNG/JPEG file,
  // so we ship a PNG copy of the website logo inside /public and embed it directly.
  const logoPath = path.join(process.cwd(), "public", "routine-hub-logo.png");
  const logoSize = 58;
  if (fs.existsSync(logoPath)) {
    doc.image(logoPath, left, 29, { fit: [logoSize, logoSize] });
  } else {
    // Safe fallback if the logo asset is accidentally removed in a deployment.
    doc.roundedRect(left, 34, 46, 46, 10).fill(C.navy);
    doc.fillColor(C.white).font("Helvetica-Bold").fontSize(15)
      .text("RH", left, 49, { width: 46, align: "center" });
  }
  doc.fillColor(C.navy).font("Helvetica-Bold").fontSize(20)
    .text("ROUTINE", left + 68, 37);
  doc.fillColor(C.blue).font("Helvetica-Bold").fontSize(20)
    .text("HUB", left + 68, 60);
  doc.fillColor(C.muted).font("Helvetica").fontSize(6.8)
    .text("Smart Class Schedule System", left + 68, 83);

  doc.fillColor(C.muted).font("Helvetica").fontSize(7.2)
    .text("Generated By", right - 105, 20, { width: 105, align: "right" });
  doc.roundedRect(right - 68, 34, 68, 45, 8).lineWidth(1).strokeColor(C.lightLine).stroke();
  doc.fillColor(C.navy).font("Helvetica-Bold").fontSize(10)
    .text("Routine", right - 68, 47, { width: 68, align: "center" });
  doc.fillColor(C.blue).font("Helvetica-Bold").fontSize(10)
    .text("Hub", right - 68, 61, { width: 68, align: "center" });
  const sourceVersion = displaySourceVersion(opts.version?.name || "");
  doc.fillColor(C.muted).font("Helvetica").fontSize(6.8)
    .text(`Version ${sourceVersion}`, right - 88, 84, { width: 88, align: "right" });

  doc.fillColor(C.ink).font("Helvetica-Bold").fontSize(21)
    .text(opts.title, left, 102, { width: contentW, align: "center" });
  doc.fillColor(C.blue).font("Helvetica-Bold").fontSize(13)
    .text(clean(opts.subject), left, 132, { width: contentW, align: "center" });

  doc.moveTo(left, 157).lineTo(right, 157).lineWidth(1).strokeColor(C.blue2).stroke();

  const tableTop = 170;
  const headerH = 28;
  const footerY = H - 34;

  // Determine a compact row height that guarantees one PDF page.
  const totalEntries = Math.max(1, groups.reduce((n, g) => n + g.entries.length, 0));
  const availableRowsH = footerY - (tableTop + headerH) - 8;
  let baseRowH = Math.floor(availableRowsH / totalEntries);
  baseRowH = Math.max(15, Math.min(26, baseRowH));

  // If there are many entries, reduce font size but keep every class on one page.
  const fontSize = baseRowH <= 16 ? 6.5 : baseRowH <= 18 ? 7 : 8;
  const headerFont = baseRowH <= 16 ? 8 : 9;

  function rowHeightFor(e: Entry) {
    const course = displayCourse(e.courseSection, e.courseName) || "—";
    const courseH = doc.font("Helvetica").fontSize(fontSize)
      .heightOfString(course, { width: widths[1] - 12, lineGap: 0 });
    const roomH = doc.font("Helvetica").fontSize(fontSize)
      .heightOfString(clean(e.room) || "—", { width: widths[3] - 10, align: "center", lineGap: 0 });
    return Math.max(baseRowH, Math.ceil(Math.max(courseH, roomH) + 7));
  }

  // First calculate all natural row heights, then proportionally compress if needed.
  const measured = groups.map((g) => g.entries.map(rowHeightFor));
  const naturalTotal = measured.flat().reduce((a, b) => a + b, 0);
  const maxTotal = footerY - (tableTop + headerH) - 8;
  const scale = naturalTotal > maxTotal ? maxTotal / naturalTotal : 1;
  const rowHeights = measured.map((rows) => rows.map((h) => Math.max(14, Math.floor(h * scale))));

  // ---------- 5-column table ----------
  let y = tableTop;
  doc.rect(left, y, contentW, headerH).fill(C.navy);
  let hx = left;
  for (let i = 0; i < widths.length; i++) {
    doc.strokeColor(C.white).lineWidth(0.55).rect(hx, y, widths[i], headerH).stroke();
    doc.fillColor(C.white).font("Helvetica-Bold").fontSize(headerFont)
      .text(labels[i], hx + 4, y + 8, { width: widths[i] - 8, align: "center" });
    hx += widths[i];
  }
  y += headerH;

  groups.forEach((group, gi) => {
    const rows = group.entries;
    const heights = rowHeights[gi];
    const groupH = heights.reduce((a, b) => a + b, 0);

    // Merged Day cell spanning every class sub-row for that day.
    doc.rect(left, y, widths[0], groupH).fill(gi % 2 ? C.soft : C.white);
    doc.strokeColor(C.line).lineWidth(0.7).rect(left, y, widths[0], groupH).stroke();
    const dayTextY = y + Math.max(4, (groupH - 11) / 2);
    doc.fillColor(C.ink).font("Helvetica-Bold").fontSize(fontSize + 0.6)
      .text(group.day, left + 4, dayTextY, { width: widths[0] - 8, align: "center" });

    let rowY = y;
    rows.forEach((entry, ri) => {
      const h = heights[ri];
      const values = [
        displayCourse(entry.courseSection, entry.courseName) || "—",
        clean(entry.time) || "—",
        clean(entry.room) || "—",
        clean(entry.teacher) || "—",
      ];
      let x = left + widths[0];

      for (let col = 1; col < 5; col++) {
        const w = widths[col];
        doc.rect(x, rowY, w, h).fill(gi % 2 ? "#FBFCFE" : C.white);
        doc.strokeColor(C.lightLine).lineWidth(0.45).rect(x, rowY, w, h).stroke();

        const center = col !== 1;
        const value = values[col - 1];
        const valueFont = col === 1 ? fontSize : Math.max(6.3, fontSize - 0.2);
        const textH = doc.font(col === 1 ? "Helvetica" : "Helvetica-Bold").fontSize(valueFont)
          .heightOfString(value, { width: w - 10, align: center ? "center" : "left", lineGap: 0 });
        doc.fillColor(col === 4 ? C.blue2 : C.ink)
          .font(col === 1 ? "Helvetica" : "Helvetica-Bold")
          .fontSize(valueFont)
          .text(value, x + 5, rowY + Math.max(3, (h - textH) / 2), {
            width: w - 10,
            align: center ? "center" : "left",
            lineGap: 0,
          });
        x += w;
      }
      rowY += h;
    });

    // Strong separator after each day group, matching the requested grouped-row style.
    doc.moveTo(left, y + groupH).lineTo(right, y + groupH)
      .lineWidth(0.9).strokeColor(C.line).stroke();
    y += groupH;
  });

  // Footer stays on the same single page.
  doc.moveTo(left, footerY - 7).lineTo(right, footerY - 7).lineWidth(0.9).strokeColor(C.blue2).stroke();
  doc.fillColor(C.muted).font("Helvetica").fontSize(6.8)
    .text(`Generated On: ${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}`, left, footerY + 5);
  doc.fillColor(C.navy).font("Helvetica-Bold").fontSize(6.8)
    .text("Routine Hub System", left, footerY + 5, { width: contentW, align: "center" });
  doc.fillColor(C.muted).font("Helvetica").fontSize(6.8)
    .text("Page 1 of 1", right - 75, footerY + 5, { width: 75, align: "right" });

  doc.end();
  return { buffer: await done, filename: opts.filename };
}
