import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
import { displayCourseName } from "../data/routine";
import { mergeConsecutiveLabEntries, routineTimeKey } from "./routine-merge";

type Entry = {
  day: string;
  time: string;
  courseSection: string;
  teacher: string;
  room: string;
  courseName?: string;
};

const DAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const clean = (v: unknown) => String(v ?? "").replace(/\s+/g, " ").trim();

function dayIndex(day: string) {
  const i = DAYS.findIndex((d) => d.toLowerCase() === clean(day).toLowerCase());
  return i === -1 ? 99 : i;
}

function timeRange(value: string) {
  const raw = clean(value);
  const parts = raw.split(/\s*(?:-|–|—|to)\s*/i).filter(Boolean);
  if (parts.length < 2) return null;

  const parseClock = (part: string) => {
    const m = part.toUpperCase().match(/^(\d{1,2})\s*[:.]\s*(\d{2})\s*(AM|PM)?$/);
    if (!m) return null;
    let hour = Number(m[1]);
    const minute = Number(m[2]);
    const suffix = m[3];
    if (suffix === "PM" && hour < 12) hour += 12;
    else if (suffix === "AM" && hour === 12) hour = 0;
    else if (!suffix && hour >= 1 && hour <= 4) hour += 12;
    return hour * 60 + minute;
  };

  const start = parseClock(parts[0]);
  let end = parseClock(parts[1]);
  if (start == null || end == null) return null;
  while (end <= start) end += 12 * 60;
  return { start, end, raw };
}

function timeKey(value: string) {
  return routineTimeKey(value);
}

function displayCourse(value: string, explicitName?: string) {
  return displayCourseName(value, explicitName);
}

function groupEntries(entries: Entry[]) {
  const sorted = mergeConsecutiveLabEntries(
    [...entries].sort((a, b) => {
      const d = dayIndex(a.day) - dayIndex(b.day);
      if (d) return d;
      const t = timeKey(a.time) - timeKey(b.time);
      if (t) return t;
      return clean(a.courseSection).localeCompare(clean(b.courseSection));
    }),
  );

  const groups: { day: string; entries: Entry[] }[] = [];
  for (const entry of sorted) {
    const day = clean(entry.day) || "Unknown";
    let group = groups.find((item) => item.day.toLowerCase() === day.toLowerCase());
    if (!group) {
      group = { day, entries: [] };
      groups.push(group);
    }
    group.entries.push(entry);
  }
  return groups;
}

function formatDuration(minutes: number) {
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  if (h && m) return `${h}h ${m}m`;
  if (h) return `${h}h`;
  return `${m}m`;
}


export async function buildRoutinePdf(opts: {
  title: string;
  subject: string;
  version: { name: string };
  entries: Entry[];
  filename: string;
  teacherMode?: boolean;
}) {
  const groups = groupEntries(opts.entries);
  const totalClasses = groups.reduce((sum, group) => sum + group.entries.length, 0);
  const chunks: Buffer[] = [];

  // Keep the reference template: clean A4 landscape, one page, strong blue table.
  const doc = new PDFDocument({
    size: "A4",
    layout: "landscape",
    margin: 0,
    info: { Title: `${opts.title} - ${opts.subject}`, Author: "Routine Hub" },
    bufferPages: false,
  });

  doc.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  const W = 841.89;
  const H = 595.28;
  const left = 58;
  const right = W - 58;
  const contentW = right - left;

  const C = {
    blue: "#0A16F5",
    blueDark: "#0E2F70",
    text: "#101828",
    muted: "#52606D",
    line: "#1F2937",
    softLine: "#8F9AAA",
    zebra: "#F3F6FA",
    softBlue: "#EAF0FF",
    white: "#FFFFFF",
  };

  const logoPath = path.join(process.cwd(), "public", "pdf-diu-logo.png");
  const qrPath = path.join(process.cwd(), "public", "pdf-generator-qr.png");

  // Header assets follow the user's reference: DIU branding on the left, QR on the right.
  if (fs.existsSync(logoPath)) {
    doc.image(logoPath, left + 8, 34, { fit: [248, 82] });
  }

  doc.fillColor(C.text).font("Times-Roman").fontSize(7.6)
    .text("Generated By", right - 82, 30, { width: 82, align: "center" });
  if (fs.existsSync(qrPath)) {
    doc.image(qrPath, right - 82, 48, { fit: [74, 74] });
  }
  doc.fillColor(C.text).font("Times-Roman").fontSize(7.5)
    .text("Routine Hub", right - 92, 124, { width: 92, align: "center" });

  const sourceVersion = clean(opts.version?.name || "");
  const versionMatch = sourceVersion.match(/\bversion\s+(.+)$/i);
  const version = versionMatch ? versionMatch[1].trim() : (sourceVersion.match(/\bv?\d+(?:\.\d+)*(?:[a-z])?\b/i)?.[0] ?? sourceVersion);
  doc.fillColor(C.muted).font("Times-Roman").fontSize(7)
    .text(version ? version.toUpperCase() : "1.1", right - 70, 156, { width: 70, align: "right" });

  doc.fillColor(C.text).font("Times-Bold").fontSize(20)
    .text(`Class Schedule : ${clean(opts.subject)}`, left, 166, { width: contentW, align: "center" });

  const labels = ["Day", "Course", "Time Slot", "Room", "Teacher"];
  const tableTop = 214;
  const headerH = 26;
  const tableBottom = 520;
  const footerY = 548;

  // Table layout: size each column from the actual content so the Course column
  // does not keep an oversized empty area. The whole table is centered.
  const allEntries = groups.flatMap((group) => group.entries);
  const headerFont = 14.2;
  const tableFont = 9.6;
  const cellPad = 12;

  const measure = (text: string, size: number, font = "Times-Bold") => {
    doc.font(font).fontSize(size);
    return doc.widthOfString(clean(text));
  };

  const maxDayW = Math.max(
    measure("Day", headerFont),
    ...groups.map((g) => measure(g.day, tableFont + 0.4)),
  );
  const maxCourseW = Math.max(
    measure("Course", headerFont),
    ...allEntries.map((entry) => measure(displayCourse(entry.courseSection, entry.courseName) || "—", tableFont)),
  );
  const maxTimeW = Math.max(
    measure("Time Slot", headerFont),
    ...allEntries.map((entry) => measure(clean(entry.time) || "—", tableFont)),
  );
  const maxRoomW = Math.max(
    measure("Room", headerFont),
    ...allEntries.map((entry) => measure(clean(entry.room) || "—", tableFont)),
  );
  const maxTeacherW = Math.max(
    measure("Teacher", headerFont),
    ...allEntries.map((entry) => measure(clean(entry.teacher) || "—", tableFont)),
  );

  const rawWidths = [
    maxDayW + cellPad,
    maxCourseW + cellPad,
    maxTimeW + cellPad,
    maxRoomW + cellPad,
    maxTeacherW + cellPad,
  ];

  let widths = rawWidths.slice();
  let tableW = widths.reduce((a, b) => a + b, 0);

  // Keep columns tightly sized to their widest content. If the combined
  // content width is larger than the printable area, scale the columns down
  // proportionally so the table still fits on one landscape page.
  if (tableW > contentW) {
    const scale = contentW / tableW;
    widths = widths.map((w) => w * scale);
    tableW = contentW;
  }

  // Center the compact content-sized table.
  const tableLeft = left + (contentW - tableW) / 2;
  const tableRight = tableLeft + tableW;

  const blocks = groups.map((group) => ({
    group,
    rows: group.entries.map((entry) => ({ kind: "class" as const, entry })),
  }));

  const totalRows = Math.max(1, blocks.reduce((sum, block) => sum + block.rows.length, 0));
  const availableH = Math.max(120, tableBottom - (tableTop + headerH));
  const rowH = Math.min(24, Math.max(9.5, availableH / totalRows));
  const bodyFont = rowH < 16 ? 7.8 : rowH < 18 ? 8.6 : 9.4;
  const metaFont = Math.max(7.6, bodyFont - 0.3);

  // Header row
  let x = tableLeft;
  doc.rect(tableLeft, tableTop, tableW, headerH).fill(C.blue);
  labels.forEach((label, i) => {
    doc.rect(x, tableTop, widths[i], headerH).lineWidth(0.55).strokeColor(C.white).stroke();
    doc.fillColor(C.white).font("Times-Bold").fontSize(headerFont)
      .text(label, x + 4, tableTop + 5, { width: widths[i] - 8, align: "center", lineBreak: false });
    x += widths[i];
  });

  const bodyTop = tableTop + headerH;
  let y = bodyTop;

  blocks.forEach((block, blockIndex) => {
    const groupH = block.rows.length * rowH;
    const dayFill = blockIndex % 2 === 0 ? C.white : C.zebra;

    // Merged day cell.
    doc.rect(tableLeft, y, widths[0], groupH).fill(dayFill);
    doc.rect(tableLeft, y, widths[0], groupH).lineWidth(0.6).strokeColor(C.line).stroke();
    doc.fillColor(C.text).font("Times-Bold").fontSize(Math.max(8.2, Math.min(10.5, bodyFont + 1)))
      .text(block.group.day, tableLeft + 4, y + Math.max(4, groupH / 2 - 5), {
        width: widths[0] - 8,
        align: "center",
        lineBreak: false,
      });

    let rowY = y;
    block.rows.forEach((row, rowIndex) => {
      const baseFill = rowIndex % 2 === 0 ? C.white : C.zebra;
      const columnsX = [
        tableLeft + widths[0],
        tableLeft + widths[0] + widths[1],
        tableLeft + widths[0] + widths[1] + widths[2],
        tableLeft + widths[0] + widths[1] + widths[2] + widths[3],
      ];

      const values = [
        displayCourse(row.entry.courseSection, row.entry.courseName) || "—",
        clean(row.entry.time) || "—",
        clean(row.entry.room) || "—",
        clean(row.entry.teacher) || "—",
      ];

      for (let col = 1; col <= 4; col += 1) {
        const cellX = columnsX[col - 1];
        const cellW = widths[col];
        doc.rect(cellX, rowY, cellW, rowH).fill(baseFill);
        doc.rect(cellX, rowY, cellW, rowH).lineWidth(0.4).strokeColor(C.softLine).stroke();
        const align = col === 1 ? "left" : "center";
        const size = col === 1 ? bodyFont : metaFont;
        const value = values[col - 1];
        // All table text is Times New Roman-style bold for visual consistency.
        doc.fillColor(col === 4 ? C.blueDark : C.text).font("Times-Bold").fontSize(size)
          .text(value, cellX + 4, rowY + Math.max(2.5, rowH / 2 - size * 0.44), {
            width: Math.max(1, cellW - 8),
            align,
            lineBreak: false,
            ellipsis: true,
          });
      }
      rowY += rowH;
    });

    doc.moveTo(tableLeft, y + groupH).lineTo(tableRight, y + groupH)
      .lineWidth(0.9).strokeColor(C.line).stroke();
    y += groupH;
  });

  // Strong outside border with compact, professional grid.
  const actualTableH = y - tableTop;
  doc.lineWidth(0.85).strokeColor(C.line).rect(tableLeft, tableTop, tableW, actualTableH).stroke();

  // Footer: quiet and similar to the reference style.
  const generated = new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
  doc.fillColor(C.muted).font("Times-Roman").fontSize(6.7)
    .text(`Generated On: ${generated}`, left, footerY + 9);
  doc.fillColor(C.text).font("Times-Roman").fontSize(6.7)
    .text(`${totalClasses} classes`, left, footerY + 9, { width: contentW, align: "center" });
  doc.fillColor(C.muted).font("Times-Roman").fontSize(6.7)
    .text("Page 1 of 1", right - 70, footerY + 9, { width: 70, align: "right" });

  doc.end();
  return { buffer: await done, filename: opts.filename };
}
